/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lens(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/lens.glb')

  materials.Mat.wireframe = false
  materials.Chrome.wireframe = false
  materials.Gold.wireframe = false
  materials['Camera-Lens'].wireframe = false

  return (
    <group ref={groupRef} {...props} dispose={null}
      scale={0.05}
      position={[-0.7, -2, 0]}
      rotation={[0.9, 4, -5.6]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.texLens02_matt001.geometry}
        material={materials.Mat}
        position={[22.887, -13.884, -59.233]}

      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.texLens02_glossy.geometry}
        material={materials.Mat}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.texLens02_matt.geometry}
        material={materials.Mat}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chromeBrushed_lens02.geometry}
        material={materials.Chrome}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chromeBrushed_lens_screws02.geometry}
        material={materials.Chrome}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gold_connectors_lens02.geometry}
        material={materials.Gold}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glassLens02.geometry}
        material={materials['Camera-Lens']}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.white_emount.geometry}
        material={materials['Mat.1']}
        position={[-0.028, 8.558, 27.38]}
      />
    </group>
  )
}

useGLTF.preload('/lens.glb')