/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LensClay(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/lens-clay.glb')

  return (
    <group ref={groupRef} {...props} dispose={null}
      scale={0.05}
      position={[-0.7, -2, 0]}
      rotation={[0.9, 4, -5.6]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.texLens02_matt001.geometry}
        material={nodes.texLens02_matt001.material}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.texLens02_glossy.geometry}
        material={nodes.texLens02_glossy.material}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.texLens02_matt.geometry}
        material={nodes.texLens02_matt.material}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chromeBrushed_lens02.geometry}
        material={nodes.chromeBrushed_lens02.material}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chromeBrushed_lens_screws02.geometry}
        material={nodes.chromeBrushed_lens_screws02.material}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gold_connectors_lens02.geometry}
        material={nodes.gold_connectors_lens02.material}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glassLens02.geometry}
        material={nodes.glassLens02.material}
        position={[22.887, -13.884, -59.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.white_emount.geometry}
        material={nodes.white_emount.material}
        position={[-0.028, 8.558, 27.38]}
      />
    </group>
  )
}

useGLTF.preload('/lens-clay.glb')