import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  // title: "Mobius",
  // description: "Generated by Mobius",
  title: "Expert 3d Modeling Services And 3D Animation Services - Mobius",
  description: "Get expert 3d modeling services tailored to your project to the next level. Our skilled 3d modeling artist, 3d animation artist bring your vision to life.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="canonical" href="https://www.mobiusstudios.co/" />
      <link rel="canonical" href="https://www.mobiusstudios.co/carrers" />
      <link rel="canonical" href="https://www.mobiusstudios.co/connect-us" />
      <link rel="canonical" href="https://www.mobiusstudios.co/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2" />
      <link rel="canonical" href="https://www.mobiusstudios.co/case-study" />
        {/* Add Clarity script here */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "mfdkxv9e0n");`,
          }}
        />

        {/* <!-- Google Tag Manager --> */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
                (function(w,d,s,l,i){
                  w[l]=w[l]||[];
                  w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
                  var f=d.getElementsByTagName(s)[0],
                  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
                  j.async=true;
                  j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
                  f.parentNode.insertBefore(j,f);
                })(window,document,'script','dataLayer','GTM-WHTLHHQK');
              `,
          }}
        />
        {/* <script
        dangerouslySetInnerHTML={{
          __html: `
                 (function(w,d,s,r,n){w.TrustpilotObject=n;w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)};
            a=d.createElement(s);a.async=1;a.src=r;a.type='text/java'+s;f=d.getElementsByTagName(s)[0];
            f.parentNode.insertBefore(a,f)})(window,document,'script', 'https://invitejs.trustpilot.com/tp.min.js', 'tp');
            tp('register', '6ZPuvh25Jszax5NL');
          `,
        }}
      /> */}
        <script>
          {`
        
        (function(w,d,s,r,n){w.TrustpilotObject=n;w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)};
            a=d.createElement(s);a.async=1;a.src=r;a.type='text/java'+s;f=d.getElementsByTagName(s)[0];
            f.parentNode.insertBefore(a,f)})(window,document,'script', 'https://invitejs.trustpilot.com/tp.min.js', 'tp');
            tp('register', '6ZPuvh25Jszax5NL');
        `}
        </script>

        {/* <!-- TrustBox script --> */}
        <script
          type="text/javascript"
          src="//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js"
          async
        ></script>
        {/* <!-- End TrustBox script --> */}
      </head>
      <body className={inter.className}>
        {/* Google Tag Manager (noscript) */}
        <noscript
          dangerouslySetInnerHTML={{
            __html: `
                <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WHTLHHQK"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe>
              `,
          }}
        />
        {/* End Google Tag Manager (noscript) */}
        <div>
          {children}
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
